name: hello-world-mini
region: nyc
static_sites:
  - name: hello-world-mini
    github:
      repo: Control-B/hello-world
      branch: main
      deploy_on_push: true
    source_dir: /
    instance_size_slug: basic-xxs
    routes:
      - path: /
    catchall_document: index.html 