name: hello-world-mini
region: nyc
static_sites:
  - name: hello-world-mini
    github:
      repo: Control-B/hello-world
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: dist
    source_dir: /
    environment_slug: node-js
    instance_size_slug: basic-xxs
    routes:
      - path: / 